
// import fetch from '@/lib/fetch'

import request from '@/lib/request'

export default function query(args) {
  const { q, offset = 0, count = 100 } = args
  const params = { q, offset, count }
  return request('/search', { params })
}

// export default function query() {
//   return Promise.resolve(
//     [{
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.0', name: 'Bad (album) - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad_(album)', about: [{ name: 'Bad' }, { name: 'Bad' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad_(album)', snippet: "Bad is the seventh studio album by American singer and songwriter Michael Jackson. It was released on August 31, 1987 in the United States by Epic Records and internationally by CBS Records, nearly five years after Jackson's previous album, Thriller.", snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-13T16:11:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.1', name: 'Bad - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad', about: [{ name: 'Bad' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad', snippet: 'Bad, a 1987 album by Michael Jackson Bad 25, a 2012 special 25th anniversary edition of the Jackson album "Bad", a single from the 2011 album Symphony Soldier by The Cab; BAD, or Bigger and Deffer, the second album by LL Cool J, 1987; Songs "Bad" (Michael Jackson song), a song from Bad, 1987', snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, deepLinks: [{ name: 'Unhealthy', url: 'https://en.wikipedia.org/wiki/Unhealthy' }, { name: 'Album', url: 'https://en.wikipedia.org/wiki/Bad_(album)' }], dateLastCrawled: '2019-09-13T11:09:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.2', name: 'Bad (Michael Jackson song) - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad_(Michael_Jackson_song)', about: [{ name: 'Bad' }, { name: 'Bad' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad_(Michael_Jackson_song)', snippet: "\"Bad\" is a song by American recording artist Michael Jackson. It was released by Epic Records on September 7, 1987 as the second single from Jackson's third major-label and seventh studio album of the same name.The song was written and composed by Jackson, and produced by Quincy Jones and Jackson. Jackson stated that the song was influenced by a real-life story he had read about, of a young ...", snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-12T14:19:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.3', name: 'Breaking Bad - Wikipedia', url: 'https://en.wikipedia.org/wiki/Breaking_Bad', about: [{ name: 'Breaking Bad' }, { name: 'Breaking Bad' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Breaking_Bad', snippet: 'Breaking Bad is an American neo-Western crime drama television series created and produced by Vince Gilligan. The show originally aired on AMC for five seasons, from January 20, 2008, to September 29, 2013.', snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-15T03:29:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.4', name: 'El Camino: A Breaking Bad Movie - Wikipedia', url: 'https://en.wikipedia.org/wiki/El_Camino:_A_Breaking_Bad_Movie', isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/El_Camino:_A_Breaking_Bad_Movie', snippet: 'El Camino: A Breaking Bad Movie is an upcoming 2019 American neo-western crime drama film written and directed by Vince Gilligan and starring Aaron Paul.The film will serve as a continuation of the television series Breaking Bad and is set to be released on Netflix on October 11, 2019, and will be broadcast at a later date on AMC.', snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-13T02:14:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.5', name: 'Bad Moms - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad_Moms', about: [{ name: 'Bad Moms' }, { name: 'Bad Moms' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad_Moms', snippet: 'Bad Moms is a 2016 American comedy film directed and written by Jon Lucas and Scott Moore.The film stars an ensemble cast that includes Mila Kunis, Kristen Bell, Kathryn Hahn, Jay Hernandez, Annie Mumolo, Jada Pinkett Smith, and Christina Applegate.. Principal photography began on January 11, 2016, in New Orleans.The film premiered on July 19, 2016, in New York City and was theatrically ...', snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-12T08:16:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.6', name: 'Bad Guy (Billie Eilish song) - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad_Guy_(Billie_Eilish_song)', about: [{ name: 'Bad Guy' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad_Guy_(Billie_Eilish_song)', snippet: "\"Bad Guy\" (stylized in all lowercase) is a song recorded by American singer-songwriter Billie Eilish. Darkroom and Interscope Records released it as the fifth single from her debut studio album When We All Fall Asleep, Where Do We Go? on March 29, 2019. Eilish and her brother Finneas O'Connell co-wrote \"Bad Guy\", with the latter producing it and the former providing additional production.", snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-12T11:10:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.7', name: 'Breaking Bad Wiki | FANDOM powered by Wikia', url: 'https://breakingbad.fandom.com/wiki/Breaking_Bad_Wiki', about: [{ name: 'Breaking Bad' }], isFamilyFriendly: true, displayUrl: 'https://breakingbad.fandom.com', snippet: 'Breaking Bad and Better Call Saul characters, cast, seasons, episodes, and information are catalogued in the Breaking Bad Wiki, a comprehensive database.', dateLastCrawled: '2019-09-12T18:11:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.8', name: 'Wikipedia', url: 'https://www.wikipedia.org/', about: [{ name: 'Wikipedia' }], isFamilyFriendly: true, displayUrl: 'https://www.wikipedia.org', snippet: 'Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation.', dateLastCrawled: '2019-09-12T20:25:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.9', name: 'The Top 10 Reasons Students Cannot Cite or Rely On Wikipedia', url: 'http://www.findingdulcinea.com/news/education/2010/march/The-Top-10-Reasons-Students-Cannot-Cite-or-Rely-on-Wikipedia.html', isFamilyFriendly: true, displayUrl: 'www.findingdulcinea.com/news/education/2010/march/...Cannot-Cite-or-Rely-on-Wikipedia.html', snippet: "According to Wikipedia itself, â€œ[W]hile some articles are of the highest quality of scholarship, others are admittedly complete rubbish. â€¦ use [Wikipedia] with an informed understanding of what it is and what it isn't.â€ To help you develop such an understanding, we present 10 reasons you can't rely on information in Wikipedia.", dateLastCrawled: '2019-09-14T01:48:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.10', name: 'Bad - Simple English Wikipedia, the free encyclopedia', url: 'https://simple.wikipedia.org/wiki/Bad', about: [{ name: 'Bad' }], isFamilyFriendly: true, displayUrl: 'https://simple.wikipedia.org/wiki/Bad', snippet: 'Bad is an album by Michael Jackson.It was released in 1987 by Epic Records.It is one of the 20 best-selling albums of all time and the ninth best-selling album ever in the UK. 9 out of the 11 songs on the album were released as singles, 10 had music videos, and five reached number one in the US Billboard Hot 100.This was the most number ones an artist had ever had from one album.', snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-08T16:07:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.11', name: 'Bad Wildbad - Wikipedia', url: 'https://en.wikipedia.org/wiki/Bad_Wildbad', about: [{ name: 'Bad Wildbad' }, { name: 'Bad Wildbad' }], isFamilyFriendly: true, displayUrl: 'https://en.wikipedia.org/wiki/Bad_Wildbad', snippet: "Bad Wildbad is a town in Germany, in the state of Baden-WÃ¼rttemberg.It is located in the government district (Regierungsbezirk) of Karlsruhe and in the district of Calw.Its coordinates are 48Â° 45' N, 8Â° 33' E. About 11,250 people live there. The current mayor is Klaus Mack.", snippetAttribution: { license: { name: 'CC-BY-SA', url: 'http://creativecommons.org/licenses/by-sa/3.0/' }, licenseNotice: 'Text under CC-BY-SA license' }, dateLastCrawled: '2019-09-15T07:58:00.0000000Z', language: 'en', isNavigational: false,
//     }, {
//       id: 'https://api.cognitive.microsoft.com/api/v7/#WebPages.12', name: 'Bad | OnePunch-Man Wiki | FANDOM powered by Wikia', url: 'https://onepunchman.fandom.com/wiki/Bad', isFamilyFriendly: true, displayUrl: 'https://onepunchman.fandom.com/wiki/Bad', snippet: 'Bad (ãƒãƒƒãƒ‰, Baddo), also known by his hero alias Metal Bat (é‡‘å±žãƒãƒƒãƒˆ, Kinzoku Batto), is the S-Class Rank 15 professional hero of the Hero Association. Metal Bat is a young man with black hair styled in a pompadour, and dark eyes that emphasize his hot temper. He wears black bontan pants and a black...', dateLastCrawled: '2019-09-12T01:41:00.0000000Z', language: 'en', isNavigational: false,
//     }],
//   )
// }
